In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
import keyword
import math as m
%matplotlib inline

In [2]:
def fibonacci(N):
    a=0
    b=1
    L = []
    while len(L) < N:
        a, b = b, a + b
        L.append(a)
    return L

In [3]:
fibonacci(10)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

In [4]:
c=np.random.randint(0,100,(4,8))
c

array([[53,  5, 52, 78, 47, 37, 43, 42],
       [35, 93, 43, 36, 47, 43, 45, 50],
       [25, 83, 31, 44, 22, 92,  4, 92],
       [36, 28, 39, 27,  1, 66, 47, 76]])

In [5]:
nrow,ncol=c.shape
print(nrow,ncol)

4 8


In [6]:
for irow in range(nrow):
    m=0
    for jcol in range(ncol):
        if c[irow,jcol]>m:
            m=c[irow,jcol]
    print('the max of row ',irow,'is',m)
 

the max of row  0 is 78
the max of row  1 is 93
the max of row  2 is 92
the max of row  3 is 76


In [7]:
c

array([[53,  5, 52, 78, 47, 37, 43, 42],
       [35, 93, 43, 36, 47, 43, 45, 50],
       [25, 83, 31, 44, 22, 92,  4, 92],
       [36, 28, 39, 27,  1, 66, 47, 76]])

In [8]:
for jcol in range(ncol):
    m=0
    for irow in range(nrow):
        if c[irow,jcol]>m:
            m=c[irow,jcol]
    print('the max of col ',jcol,'is',m)

the max of col  0 is 53
the max of col  1 is 93
the max of col  2 is 52
the max of col  3 is 78
the max of col  4 is 47
the max of col  5 is 92
the max of col  6 is 47
the max of col  7 is 92


In [9]:
# max of thr rows
np.max(c,1)

array([78, 93, 92, 76])

In [10]:
# max of column
np.max(c,0)

array([53, 93, 52, 78, 47, 92, 47, 92])

In [11]:
def sqrt(b):
    """return the square root of b"""
    return (b)**(1/2)
def quadratic(a,b,c):
    z=sqrt(b**2 - 4*a*c)
    return (-b+z)/2*a,(-b-z)/2*a

In [12]:
quadratic(1,2,3)

((-0.9999999999999999+1.4142135623730951j), (-1-1.4142135623730951j))

In [13]:
test="To analyze statistical significance of the difference between the Mean Temperatures of Male and Female, we will use t-statistic with t-test. A t-test’s statistical significance indicates whether or not the difference between two groups’ averages most likely reflects a “real” difference in the population from which the groups were sampled.A one-sample t-test checks whether a sample mean differs from the population(whole data) mean. two-sample t-test investigates whether the means of two independent data samples differ from one another. In a two-sample test, the null hypothesis is that the means of both groups are the same.In our case, since we to compare two variables Male and Female, we will use two-sample t-test.T- tests are supported by P-Value. A p-value is used in hypothesis testing to help you support or reject the null hypothesis. The p-value is the evidence against a null hypothesis. The smaller the p-value, the strong the evidence that you should reject the null hypothesis.P-values are expressed as decimals although it may be easier to understand what they are if you convert them to a percentage. For example, a p value of 0.0254 is 2.54%. This means there is a 2.54% chance your results could be random (i.e. happened by chance). That’s pretty tiny. On the other hand, a large p-value of .9(90%) means your results have a 90% probability of being completely random and not due to anything in your experiment. Therefore, the smaller thep-value, the more important (“significant”) your results.[5]"

In [14]:
print(test)

To analyze statistical significance of the difference between the Mean Temperatures of Male and Female, we will use t-statistic with t-test. A t-test’s statistical significance indicates whether or not the difference between two groups’ averages most likely reflects a “real” difference in the population from which the groups were sampled.A one-sample t-test checks whether a sample mean differs from the population(whole data) mean. two-sample t-test investigates whether the means of two independent data samples differ from one another. In a two-sample test, the null hypothesis is that the means of both groups are the same.In our case, since we to compare two variables Male and Female, we will use two-sample t-test.T- tests are supported by P-Value. A p-value is used in hypothesis testing to help you support or reject the null hypothesis. The p-value is the evidence against a null hypothesis. The smaller the p-value, the strong the evidence that you should reject the null hypothesis.P-va

In [15]:
def countletters(letter,text):
    count=0
    for a in text:
        if a.lower==letter.lower:
            count+=1
    return count

In [16]:
countletters("a",test),countletters("b",test)

(97, 11)

In [17]:
alpha="abcdefghijklmnopqrstuvwxyz"
for letter in alpha:
    print("the letter",letter,"appaers",countletters(letter,test),"text")

the letter a appaers 97 text
the letter b appaers 11 text
the letter c appaers 32 text
the letter d appaers 29 text
the letter e appaers 182 text
the letter f appaers 26 text
the letter g appaers 16 text
the letter h appaers 65 text
the letter i appaers 64 text
the letter j appaers 2 text
the letter k appaers 2 text
the letter l appaers 59 text
the letter m appaers 34 text
the letter n appaers 66 text
the letter o appaers 69 text
the letter p appaers 43 text
the letter q appaers 0 text
the letter r appaers 62 text
the letter s appaers 87 text
the letter t appaers 122 text
the letter u appaers 39 text
the letter v appaers 14 text
the letter w appaers 21 text
the letter x appaers 3 text
the letter y appaers 23 text
the letter z appaers 1 text


In [18]:
# series
df={"age":pd.Series([12,23,34]), "name": pd.Series(["ama","emma","mar"])}
df

{'age': 0    12
 1    23
 2    34
 dtype: int64, 'name': 0     ama
 1    emma
 2     mar
 dtype: object}

In [19]:
# data frame
df=pd.DataFrame(df)
df

age  name
0   12   ama
1   23  emma
2   34   mar

In [20]:
d=[["nam",3],["v",34],["b",3]]
pd.DataFrame(d,columns=["clo1","col2"])

clo1  col2
0  nam     3
1    v    34
2    b     3

In [21]:
d=[["a",23,45],["an",2,33],["b",25,27]]
pd.DataFrame(d,columns=["name","age","income"])

name  age  income
0    a   23      45
1   an    2      33
2    b   25      27

In [22]:
f={"name":pd.Series(["AMA","MMA","MM"],index=["male","male","female"]),
   "age":pd.Series([1,2,4],index=["male","male","female"])}
per=pd.DataFrame(f)
per

name  age
male    AMA    1
male    MMA    2
female   MM    4

In [23]:
#column addition
per["income"]=pd.DataFrame(pd.Series([234,35,71],index=["male","male","female"]))
per

name  age  income
male    AMA    1     234
male    MMA    2      35
female   MM    4      71

In [24]:
#deleting
del per['age']

In [25]:
per

name  income
male    AMA     234
male    MMA      35
female   MM      71

In [26]:
per.pop("name")

male      AMA
male      MMA
female     MM
Name: name, dtype: object

In [27]:
per

income
male       234
male        35
female      71

In [28]:
# panel

dat=np.random.rand(2,3,5)
dat

array([[[0.22854734, 0.34262627, 0.85382412, 0.07179241, 0.14536246],
        [0.63091861, 0.29465303, 0.23707298, 0.97432204, 0.71157427],
        [0.87371489, 0.82782539, 0.42229907, 0.43950022, 0.75028283]],

       [[0.41049388, 0.43720634, 0.10753363, 0.92117261, 0.22710498],
        [0.36991295, 0.54593924, 0.09293452, 0.70564968, 0.00210332],
        [0.987538  , 0.54034192, 0.3965241 , 0.38268561, 0.83810606]]])

In [29]:
d={"name":pd.Series(["rima","ama","art","yam","yea","oui","non","arima"]),
  "age":pd.Series([55,22,44,12,45,12,35,57]),
  "incom":pd.Series([123,34,124,234,45,567,12,34])}
data=pd.DataFrame(d)
data

name  age  incom
0   rima   55    123
1    ama   22     34
2    art   44    124
3    yam   12    234
4    yea   45     45
5    oui   12    567
6    non   35     12
7  arima   57     34

In [30]:
data.ndim

2

In [31]:
data.shape

(8, 3)

In [32]:
data.size

24

In [33]:
#transpose
data.T

0    1    2    3    4    5    6      7
name   rima  ama  art  yam  yea  oui  non  arima
age      55   22   44   12   45   12   35     57
incom   123   34  124  234   45  567   12     34

In [34]:
data.axes

[RangeIndex(start=0, stop=8, step=1),
 Index(['name', 'age', 'incom'], dtype='object')]

In [35]:
data.values

array([['rima', 55, 123],
       ['ama', 22, 34],
       ['art', 44, 124],
       ['yam', 12, 234],
       ['yea', 45, 45],
       ['oui', 12, 567],
       ['non', 35, 12],
       ['arima', 57, 34]], dtype=object)

In [36]:
#first 3
data.head(3)

name  age  incom
0  rima   55    123
1   ama   22     34
2   art   44    124

In [37]:
#last 4
data.tail(4)

name  age  incom
4    yea   45     45
5    oui   12    567
6    non   35     12
7  arima   57     34

# DESCRIPTIVE STATISTCS

In [38]:
# mean for numerical data
data.mean()

age       35.250
incom    146.625
dtype: float64

In [39]:
data.std()

age       18.093014
incom    184.870563
dtype: float64

In [40]:
data

name  age  incom
0   rima   55    123
1    ama   22     34
2    art   44    124
3    yam   12    234
4    yea   45     45
5    oui   12    567
6    non   35     12
7  arima   57     34

In [41]:
#summing the numerical values within rows
data.sum(1)

0    178
1     56
2    168
3    246
4     90
5    579
6     47
7     91
dtype: int64

In [42]:
#summing the numerical columns
data.sum(0)

name     rimaamaartyamyeaouinonarima
age                              282
incom                           1173
dtype: object

In [43]:
# cummulative sum
data.cumsum()

name  age incom
0                         rima   55   123
1                      rimaama   77   157
2                   rimaamaart  121   281
3                rimaamaartyam  133   515
4             rimaamaartyamyea  178   560
5          rimaamaartyamyeaoui  190  1127
6       rimaamaartyamyeaouinon  225  1139
7  rimaamaartyamyeaouinonarima  282  1173

In [44]:
data.median()

age      39.5
incom    84.0
dtype: float64

In [45]:
data.describe()

age       incom
count   8.000000    8.000000
mean   35.250000  146.625000
std    18.093014  184.870563
min    12.000000   12.000000
25%    19.500000   34.000000
50%    39.500000   84.000000
75%    47.500000  151.500000
max    57.000000  567.000000

In [46]:
#include="all" will include the descriptive statistics for non-numerical olumns
data.describe(include="all")

name        age       incom
count     8   8.000000    8.000000
unique    8        NaN         NaN
top     non        NaN         NaN
freq      1        NaN         NaN
mean    NaN  35.250000  146.625000
std     NaN  18.093014  184.870563
min     NaN  12.000000   12.000000
25%     NaN  19.500000   34.000000
50%     NaN  39.500000   84.000000
75%     NaN  47.500000  151.500000
max     NaN  57.000000  567.000000

In [47]:
s=pd.DataFrame(np.random.randn(6,3),columns=["col1","col2","col3"])
s


col1      col2      col3
0 -0.344841  0.834614  0.286070
1  0.949133  0.241942  0.385252
2  1.380239 -0.589372  0.795037
3 -0.806596  0.383177  2.035073
4  0.026618 -1.032947 -0.454352
5  0.140181  0.717095  0.320325

In [48]:
s.describe()

col1      col2      col3
count  6.000000  6.000000  6.000000
mean   0.224122  0.092418  0.561234
std    0.811714  0.745555  0.827406
min   -0.806596 -1.032947 -0.454352
25%   -0.251976 -0.381543  0.294634
50%    0.083399  0.312560  0.352788
75%    0.746895  0.633616  0.692591
max    1.380239  0.834614  2.035073

In [49]:
s.apply(np.mean)

col1    0.224122
col2    0.092418
col3    0.561234
dtype: float64

In [50]:
# couln wise
s.apply(np.mean,axis=0)

col1    0.224122
col2    0.092418
col3    0.561234
dtype: float64

In [51]:
#rowwise
s.apply(np.mean,axis=1)

0    0.258614
1    0.525442
2    0.528635
3    0.537218
4   -0.486894
5    0.392533
dtype: float64

In [52]:
s.apply(lambda x: x.max()-x.min())

col1    2.186836
col2    1.867561
col3    2.489425
dtype: float64

In [53]:
s.apply(lambda x: (x-x.mean())/x.std())

col1      col2      col3
0 -0.700940  0.995495 -0.332562
1  0.893184  0.200553 -0.212692
2  1.424291 -0.914473  0.282573
3 -1.269804  0.389990  1.781277
4 -0.243317 -1.509434 -1.227434
5 -0.103413  0.837869 -0.291163

In [54]:
s.apply(lambda x: x.mean()-x.median())

col1    0.140723
col2   -0.220141
col3    0.208446
dtype: float64

In [55]:
# applying to single colums
s["col2"].map(lambda x: x*10)

0     8.346140
1     2.419418
2    -5.893718
3     3.831774
4   -10.329475
5     7.170952
Name: col2, dtype: float64

In [56]:
s["col3"].map(lambda x: x**100)

0    4.439053e-55
1    3.753907e-42
2    1.093306e-10
3    7.211150e+30
4    5.485331e-35
5    3.622713e-50
Name: col3, dtype: float64

In [57]:
s

col1      col2      col3
0 -0.344841  0.834614  0.286070
1  0.949133  0.241942  0.385252
2  1.380239 -0.589372  0.795037
3 -0.806596  0.383177  2.035073
4  0.026618 -1.032947 -0.454352
5  0.140181  0.717095  0.320325

In [58]:
#all columns
s=s.applymap(lambda x: x*100)

In [59]:
s

col1        col2        col3
0  -34.484132   83.461396   28.607039
1   94.913266   24.194177   38.525194
2  138.023928  -58.937175   79.503714
3  -80.659631   38.317736  203.507325
4    2.661810 -103.294745  -45.435157
5   14.018052   71.709525   32.032463

In [60]:
#renaming columns and index
s.rename(columns={"col1":"colum1","col2":"colum2"},index={0:"a",1:"b"},inplace=True)

In [61]:
s

colum1      colum2        col3
a  -34.484132   83.461396   28.607039
b   94.913266   24.194177   38.525194
2  138.023928  -58.937175   79.503714
3  -80.659631   38.317736  203.507325
4    2.661810 -103.294745  -45.435157
5   14.018052   71.709525   32.032463

In [65]:
#to sort columns
s.sort_values(by="col3")

colum1      colum2        col3
4    2.661810 -103.294745  -45.435157
a  -34.484132   83.461396   28.607039
5   14.018052   71.709525   32.032463
b   94.913266   24.194177   38.525194
2  138.023928  -58.937175   79.503714
3  -80.659631   38.317736  203.507325

In [68]:
s.dtypes

colum1    float64
colum2    float64
col3      float64
dtype: object

In [69]:
s.index

Index(['a', 'b', 2, 3, 4, 5], dtype='object')